version: "3.7"
services: 
    app:
        build: 
            context: ./
            dockerfile: Dockerfile
        image: parallaxdev1/landing
        container_name: landing-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes: 
            - ./src/:/var/www/html
        networks: 
            - landing-net
    
    nginx:
        image: nginx:1.17-alpine
        container_name: landing-web
        restart: unless-stopped
        ports: 
            - 8001:80
        volumes: 
            - ./nginx/etc/conf.d/:/etc/nginx/conf.d/
            - ./src/:/var/www/html
        networks: 
            - landing-net

networks: 
    landing-net:
        driver: bridge